name: publish

on:
  push:
    tags:
      - "*" # This triggers on any tag push

jobs:
  # Linux Build Job
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          override: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libwebkit2gtk-4.0-dev libgtksourceview-4-dev libsoup2.4-dev libssl-dev libsqlite3-dev -y

      - name: Install Diesel CLI
        run: cargo install diesel_cli --no-default-features --features sqlite

      - name: Install npm dependencies
        run: npm install

      - name: Startup a Fresh DB
        run: npm run db

      - name: Build Tauri App
        run: npm run app:build

      - name: Upload Linux Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tauri-linux-build
          path: ./src-tauri/target/release/bundle/

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install sqlite
        shell: cmd
        run: |
          choco install sqlite
          cd /D C:\ProgramData\chocolatey\lib\SQLite\tools
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          lib /machine:x64 /def:sqlite3.def /out:sqlite3.lib

      - name: Set variables for sqlite
        shell: bash
        run: |
          echo "C:\ProgramData\chocolatey\lib\SQLite\tools" >> $GITHUB_PATH
          echo "SQLITE3_LIB_DIR=C:\ProgramData\chocolatey\lib\SQLite\tools" >> $GITHUB_ENV

      - name: Install Diesel CLI
        run: cargo install diesel_cli --no-default-features --features sqlite

      - name: Install npm dependencies
        run: npm install

      - name: Startup a Fresh DB
        run: npm run db

      - name: Build Tauri App
        run: npm run app:build

      - name: Upload Windows Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tauri-windows-build
          path: ./src-tauri/target/release/bundle/
